{
 "title": "Merizosearch cluster dashboard",
 "description": "Overview of the cluster infrastructure and pipeline progress\nDeployed from Ansible\nCOMP0235",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "workers_list",
    "query": {
     "query": "label_values(node_cpu_seconds_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 8, "y": 0 },
   "options": {
    "content": "# Merizosearch pipeline cluster monitoring "
   }
  },
  { "title": "Manager health ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Manager memory usage in Megabytes ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 3 },
   "targets": [
    {
     "expr": "rate(node_memory_MemAvailable_bytes{instance=\"10.134.12.172:9100\"}[5m]) / 1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Manager Disk utilization",
   "type": "piechart",
   "description": "10.134.12.172",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{instance=\"10.134.12.172:9100\",fstype!=\"tmpfs\"}) / 1000000000",
     "legendFormat": "free"
    },
    {
     "expr": "(sum(node_filesystem_size_bytes{instance=\"10.134.12.172:9100\",fstype!=\"tmpfs\"})-sum(node_filesystem_avail_bytes{instance=\"10.134.12.172:9100\",fstype!=\"tmpfs\"})) / 1000000000",
     "legendFormat": "used"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Workers memory usage in Gigabytes ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 12 },
   "targets": [
    {
     "expr": "rate(node_memory_MemAvailable_bytes{instance!=\"10.134.12.172:9100\", instance!=\"localhost:9100\"}[5m]) / 1000000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Workers metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Worker 1 CPU usage percent",
   "type": "timeseries",
   "description": "10.134.12.147",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "100 - (\n  sum(rate(node_cpu_seconds_total{instance=\"10.134.12.147:9100\", mode=\"idle\"}[1m])) by (cpu, instance)  /\n  sum(rate(node_cpu_seconds_total{instance=\"10.134.12.147:9100\"}[1m])) by (cpu, instance)\n)*100\n",
     "legendFormat": "CPU: {{cpu}}"
    }
   ]
  },
  {
   "title": "Worker 2 CPU usage percent",
   "type": "timeseries",
   "description": "10.134.12.128",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "100 - (\n  sum(rate(node_cpu_seconds_total{instance=\"10.134.12.128:9100\", mode=\"idle\"}[1m])) by (cpu, instance)  /\n  sum(rate(node_cpu_seconds_total{instance=\"10.134.12.128:9100\"}[1m])) by (cpu, instance)\n)*100\n",
     "legendFormat": "CPU: {{cpu}}"
    }
   ]
  },
  {
   "title": "Worker 3 CPU usage percent",
   "type": "timeseries",
   "description": "10.134.12.76",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "100 - (\n  sum(rate(node_cpu_seconds_total{instance=\"10.134.12.76:9100\", mode=\"idle\"}[1m])) by (cpu, instance)  /\n  sum(rate(node_cpu_seconds_total{instance=\"10.134.12.76:9100\"}[1m])) by (cpu, instance)\n)*100\n",
     "legendFormat": "CPU: {{cpu}}"
    }
   ]
  },
  {
   "title": "Worker 1 CPU usage percent across all cores",
   "type": "timeseries",
   "description": "10.134.12.147",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "100 - (\n  sum(rate(node_cpu_seconds_total{instance=\"10.134.12.147:9100\", mode=\"idle\"}[1m]))/\n  sum(rate(node_cpu_seconds_total{instance=\"10.134.12.147:9100\"}[1m]))\n)*100\n",
     "legendFormat": "CPU: {{cpu}}"
    }
   ]
  },
  {
   "title": "Worker 2 CPU usage percent across all cores",
   "type": "timeseries",
   "description": "10.134.12.128",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "targets": [
    {
     "expr": "100 - (\n  sum(rate(node_cpu_seconds_total{instance=\"10.134.12.128:9100\", mode=\"idle\"}[1m]))/\n  sum(rate(node_cpu_seconds_total{instance=\"10.134.12.128:9100\"}[1m]))\n)*100\n",
     "legendFormat": "CPU: {{cpu}}"
    }
   ]
  },
  {
   "title": "Worker 3 CPU usage percent across all cores",
   "type": "timeseries",
   "description": "10.134.12.76",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "targets": [
    {
     "expr": "100 - (\n  sum(rate(node_cpu_seconds_total{instance=\"10.134.12.76:9100\", mode=\"idle\"}[1m]))/\n  sum(rate(node_cpu_seconds_total{instance=\"10.134.12.76:9100\"}[1m]))\n)*100\n",
     "legendFormat": "CPU: {{cpu}}"
    }
   ]
  },
  {
   "title": "Worker 1 Disk utilization",
   "type": "piechart",
   "description": "10.134.12.147",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{instance=\"10.134.12.147:9100\",fstype!=\"tmpfs\"}) / 1000000000",
     "legendFormat": "free"
    },
    {
     "expr": "(sum(node_filesystem_size_bytes{instance=\"10.134.12.147:9100\",fstype!=\"tmpfs\"})-sum(node_filesystem_avail_bytes{instance=\"10.134.12.147:9100\",fstype!=\"tmpfs\"})) / 1000000000",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Worker 2 Disk utilization",
   "type": "piechart",
   "description": "10.134.12.128",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{instance=\"10.134.12.128:9100\",fstype!=\"tmpfs\"}) / 1000000000",
     "legendFormat": "free"
    },
    {
     "expr": "(sum(node_filesystem_size_bytes{instance=\"10.134.12.128:9100\",fstype!=\"tmpfs\"})-sum(node_filesystem_avail_bytes{instance=\"10.134.12.128:9100\",fstype!=\"tmpfs\"})) / 1000000000",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Worker 3 Disk utilization",
   "type": "piechart",
   "description": "10.134.12.76",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{instance=\"10.134.12.76:9100\",fstype!=\"tmpfs\"}) / 1000000000",
     "legendFormat": "free"
    },
    {
     "expr": "(sum(node_filesystem_size_bytes{instance=\"10.134.12.76:9100\",fstype!=\"tmpfs\"})-sum(node_filesystem_avail_bytes{instance=\"10.134.12.76:9100\",fstype!=\"tmpfs\"})) / 1000000000",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Storage node status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true
  },
  {
   "title": "Storage node Data disk utilization",
   "type": "piechart",
   "description": "10.134.12.101",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{instance=\"localhost:9100\", fstype!=\"tmpfs\", device=\"/dev/vdb1\"}) / 1000000000",
     "legendFormat": "free"
    },
    {
     "expr": "(sum(node_filesystem_size_bytes{instance=\"localhost:9100\", fstype!=\"tmpfs\", device=\"/dev/vdb1\"}) - sum(node_filesystem_avail_bytes{instance=\"localhost:9100\", fstype!=\"tmpfs\", device=\"/dev/vdb1\"})) / 1000000000",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Storage node Data disk utilization over time",
   "type": "timeseries",
   "description": "10.134.12.101",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{instance=\"localhost:9100\", fstype!=\"tmpfs\", device=\"/dev/vdb1\"}) - sum(node_filesystem_avail_bytes{instance=\"localhost:9100\", fstype!=\"tmpfs\", device=\"/dev/vdb1\"})) / 1000000000",
     "legendFormat": "used"
    }
   ]
  }
 ]
}