---
- name: Kernel source
  become: true
  ansible.builtin.dnf:
    name: "kernel-devel"
    state: latest
- name: BeeGFS Repo
  become: true
  ansible.builtin.yum_repository:
    baseurl: "https://www.beegfs.io/release/beegfs_7.4.5/dists/rhel9"
    state: present
    gpgkey: "https://www.beegfs.io/release/beegfs_7.4.5/gpg/GPG-KEY-beegfs"
    gpgcheck: true
    name: "BeeGFS"
    description: "BeeGFS repo"
- name: Install BeeGFs packages
  become: true
  ansible.builtin.dnf:
    name: 
    - "beegfs-storage"
    - "beegfs-client"
    - "beegfs-utils"
    - "beegfs-helperd"
    - "beegfs-mgmtd"
    - "beegfs-meta"
    state: latest

# host - metadata, manager
- name: configure metadata and manager on host
  import_tasks: beegfs-host.yaml
  when: inventory_hostname in groups['host']

# workers: storage, client
- name: configure storage on workers
  import_tasks: beegfs-storage.yaml
  when: inventory_hostname in groups['workers']

- name: configure beegfs client on workers
  import_tasks: beegfs-client.yaml
  when: inventory_hostname in groups['workers']

# links
- name: Make user directory
  become: true
  ansible.builtin.file:
    path: /beegfs/almalinux
    state: directory
    owner: almalinux
- name: Create home directory sym-link
  become: true
  ansible.builtin.file:
    src: /beegfs/almalinux
    dest: "/home/almalinux/beegfs🐝"
    state: link