---
name: configure nfs server
import_tasks: nfs-server.yaml
when: inventory_hostname in groups['host']

name: configure nfs client
import_tasks: nfs-client.yaml
when: inventory_hostname in groups['workers']