---
- name: configure nfs server
  import_tasks: nfs-server.yaml
  when: inventory_hostname == groups['workers'][0]

- name: configure nfs client
  import_tasks: nfs-client.yaml
  when: inventory_hostname != groups['workers'][0]