- name: Delete Existing Private Key
  ansible.builtin.file:
    state: absent 
    path: /home/almalinux/.ssh/id_ed25519
- name: Delete Existing Public Key
  ansible.builtin.file:
    state: absent 
    path: /home/almalinux/.ssh/id_ed25519.pub    
- name: Generate key
  ansible.builtin.shell: ssh-keygen -q -t ed25519 -f /home/almalinux/.ssh/id_ed25519 -C "" -N ""
- name: Add to authorized_keys
  ansible.builtin.shell: cat /home/almalinux/.ssh/id_ed25519.pub >> /home/almalinux/.ssh/authorized_keys
