---
- name: set hostnames
  become: true
  ansible.builtin.hostname:
    name: "{% if (inventory_hostname in groups['host']) %}host{% else 
      %}workernode{{lookup('ansible.utils.index_of', groups['workers'], 'eq', inventory_hostname) + 1 }}{% endif %}"
    use: systemd

- name: create cluster ssh key
  import_tasks: create-cluster-key.yaml
  when: inventory_hostname in groups['host']
- name: distribute key apair among cluster
  import_tasks: share-cluster-key.yaml
  when: inventory_hostname in groups['workers']

- name: set ssh config
  ansible.builtin.copy:
    src: ./files/ssh_config
    dest: /home/almalinux/.ssh/config

# - name: enable ufw firewall
#   import_tasks: firewall.yaml
