- name: Put public key from host to workers
  ansible.builtin.copy:
    src: /home/almalinux/.ssh/id_ed25519.pub
    dest: /home/almalinux/.ssh/id_ed25519.pub

- name: Put private key from host to workers
  ansible.builtin.copy:
    src: /home/almalinux/.ssh/id_ed25519
    dest: /home/almalinux/.ssh/id_ed25519
    mode: 0600

- name: Add to authorized_keys
  become: true
  ansible.builtin.shell: cat /home/almalinux/.ssh/id_ed25519.pub >> /home/almalinux/.ssh/authorized_keys
