- name: set up venv
  import_tasks: environment.yaml
  when: inventory_hostname in groups['workers']

- name: copy application script
  ansible.builtin.copy:
    src: files/transcribe_service_redis.py
    dest: /home/almalinux/transcribe_service_redis.py
    owner: almalinux
    group: almalinux
    mode: '0755'
  when: inventory_hostname in groups['workers']

- name: set up redis and queue monitor
  import_tasks: redis.yaml
  when: inventory_hostname == groups['workers'][0]

- name: create base log directories
  ansible.builtin.file:
    path: /home/almalinux/nfs/{{ item }}-logs
    state: directory
    mode: '0755'
  loop:
    - preprocess
    - concat
  when: inventory_hostname in groups['host']