- name: Config directory
  become: true
  ansible.builtin.file:
    path: /data/nfs/config
    state: directory
    mode: "0755"
- name: Setup Slurm conf
  become: true
  ansible.builtin.template:
    src: files/slurm.conf.j2
    dest:  /data/nfs/config/slurm.conf
    mode: "0644"
- name: Delete default slurm config
  become: true
  ansible.builtin.file:
    path: /etc/slurm/slurm.conf
    state: absent
- name: Create link to shared slurm config
  become: true
  ansible.builtin.file:
    src: /data/nfs/config/slurm.conf
    dest: /etc/slurm/slurm.conf
    state: link
- name: Start Slurmctld
  become: true
  ansible.builtin.systemd_service:
    name: slurmctld
    state: started
    enabled: true