- name: Delete default slurm config
  become: true
  ansible.builtin.file:
    path: /etc/slurm/slurm.conf
    state: absent
- name: Create link to shared slurm config
  become: true
  ansible.builtin.file:
    src: /data/nfs/config/slurm.conf
    dest: /etc/slurm/slurm.conf
    state: link
- name: Start Slurmd
  become: true
  ansible.builtin.systemd_service:
    name: slurmd
    state: started
    enabled: true