- name: Delete Existing Key
  become: true
  ansible.builtin.file:
    state: absent 
    path: /etc/munge/munge.key  
- name: Generate key
  become: true
  ansible.builtin.shell: create-munge-key
- name: Get munge keys
  become: true
  ansible.builtin.fetch:
    src: /etc/munge/munge.key
    dest: ./.generated/munge/
    flat: true
- name: Start munge
  become: true
  ansible.builtin.systemd_service:
    name: munge
    state: started
    enabled: true