#sets up the cluster infrastructure
- name: Bootstrap machines
  hosts: all
  become: true
  vars:
    do_upgrade: true
  roles:
   - role: bootstrap
    
- name: set up ssh
  hosts: all
  roles:
    - role: ssh-setup

- name: configure monitoring
  hosts: all
  vars_files: 
    - vars.yaml
  roles: 
    - role: monitoring

- name: nfs
  hosts: all
  roles:
    - role: nfs

- name: munge
  hosts: all
  become: true
  roles:
    - role: munge
- name: restart munge daemon
  hosts: host
  become: true
  tasks:
    - name: restart munge
      ansible.builtin.systemd:
        name: munge
        state: restarted
        enabled: true
    
- name: set up slurm
  hosts: all
  become: true
  roles:
    - role: slurm

- name: set up minio
  hosts: host
  vars_files:
    - vars.yaml
  roles:
    - role: minio
      vars:
        force_create_new_certs: false
- name: minio client on workers
  hosts: workers
  become: true
  vars_files:
    - vars.yaml
  tasks:
    - include_role:
        name: minio
        tasks_from: minio-client-only

- name: set up application environment
  hosts: all
  roles:
    - role: application
