# download and run the system on a new data input
# ONLY TO BE RUN AFTER SYSTEM IS SET UP COMPLETELY
- name: Download a new dataset
  hosts: host
  vars:
    dataset_name: "groks-physics"
    itemlist_file: "sample-itemlist.txt"
  roles:
    - role: dataset
  
- name: Run the system on a new data input
  hosts: all
  vars:
    dataset_name: "groks-physics"
  tasks:
    - include_role:
        name: application
        tasks_from: deploy
