# already in main
# ALL
- name: Kernel source
  become: true
  ansible.builtin.dnf:
    name: "kernel-devel"
    state: latest
- name: BeeGFS Repo
  become: true
  ansible.builtin.yum_repository:
    baseurl: "https://www.beegfs.io/release/beegfs_7.4.5/dists/rhel9"
    state: present
    gpgkey: "https://www.beegfs.io/release/beegfs_7.4.5/gpg/GPG-KEY-beegfs"
    gpgcheck: true
    name: "BeeGFS"
    description: "BeeGFS repo"
- name: Install BeeGFs packages
  become: true
  ansible.builtin.dnf:
    name: 
    - "beegfs-storage"
    - "beegfs-client"
    - "beegfs-utils"
    - "beegfs-helperd"
    - "beegfs-mgmtd"
    - "beegfs-meta"
    state: latest
