- name: generate filelist
  ansible.builtin.shell: |
    ls nfs/{{ dataset_name }}/*/*.mp3 > nfs/{{ dataset_name }}_filelist
  register: filelist

- name: create log directories
  ansible.builtin.file:
    path: /home/almalinux/nfs/{{ item }}-logs/{{ dataset_name }}
    state: directory
    mode: '0755'
  loop:
    - preprocess
    - concat

- name: create preprocess and transcribed directory
  ansible.builtin.file:
    path: /home/almalinux/nfs/{{item}}-{{ dataset_name }}
    state: directory
    mode: '0755' 
  loop:
    - preprocessed
    - transcribed

- name: inject dataset name into batch scripts # scripts placed in home directory on host
  ansible.builtin.template:
    src: templates/{{ item }}.j2
    dest: /home/almalinux/{{ item }}
    owner: almalinux
    group: almalinux
    mode: '0755'
  loop:
    - preprocess.sh
    - concatenate.sh

